### ISSUE TITLE
can we play specific track in audio streaming?

### ISSUE THREAD

**Issue by navneetgarggate6** [dabblelab/3-alexa-audio-streaming-example-skill#2]
Can we play a track specified by user like we have more than 1 track in our streaming list and user says play track intent and than we play that track only

**Comment by tingiris** [comment]
Hi @navneetgarggate6 - you could have multiple streams and the user could select the stream or you could skip to a point in a stream but you'd need to modify the template to accomplish this. It is possible, however.
